name: Clippy for all targets and all features, failing on any clippy warnings

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs: 
 
  clippy-win-base:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run clippy
      run: cargo clippy -target x86_64-pc-windows-gnu -- -D warnings