theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
  - hash_params/README.md
  - process_hollowing/README.md
  - gifs/process_hollowing.gif
