theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - hash_params/README.md
  - process_hollowing/README.md
  - process_migration/README.md
  - tcp_reverse_shell/README.md
  - xor_params/README.md
