theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "gifs"
    values:
      image: true
include:
  - README.md
  - LICENSE
  - hash_params/README.md
  - process_hollowing/README.md
