name: RCO for Unix targets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unix-builds:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build all for Unix
      run: cargo build --verbose
    - name: Build reverse shell for Unix
      run: cargo build -p tcp_reverse_shell --verbose
    - name: Build process migration for Unix
      run: cargo build -p process_migration --verbose
